[package]
name = "redragon-streamdeck"
version = "2.0.0"
description = "Redragon Stream Deck Manager - Desktop App"
authors = ["René Kuhm <renekuhm2@gmail.com>"]
license = "MIT"
repository = "https://github.com/Rene-Kuhm/redragon-streamdeck-linux"
edition = "2021"

[lib]
name = "redragon_streamdeck_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
redragon-core = { path = "../crates/core" }
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"

chrono = "0.4"
lazy_static = "1.4"
url = "2"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rdev = "0.5"
dirs = "5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
